var companies = [ { name: 'AIA Engineering Ltd.',
    industry: 'INDUSTRIAL MANUFACTURING',
    symbol: 'AIAENG',
    url: 'http://www.moneycontrol.com/india/stockpricequote/engineeringheavy/aiaengineering/AIE01',
    EPS: 62.31,
    Divident: 900,
    CurrentStockPrice: 1359.95,
    currentRatio: 5.64,
    dividentYeild: '1.33%' },
  { name: 'Cyient Ltd.',
    industry: 'IT',
    symbol: 'CYIENT',
    url: 'http://www.moneycontrol.com/india/stockpricequote/computerssoftware/cyient/IE07',
    EPS: 20.75,
    Divident: 140,
    CurrentStockPrice: 463.25,
    currentRatio: 5.46,
    dividentYeild: '1.51%' },
  { name: 'Jai Corp Ltd.',
    industry: 'INDUSTRIAL MANUFACTURING',
    symbol: 'JAICORPLTD',
    url: 'http://www.moneycontrol.com/india/stockpricequote/steelgpgcsheets/jaicorp/JC08',
    EPS: 3.9,
    Divident: 50,
    CurrentStockPrice: 72.25,
    currentRatio: 4.25,
    dividentYeild: '0.69%' },
  { name: 'Lupin Ltd.',
    industry: 'PHARMA',
    symbol: 'LUPIN',
    url: 'http://www.moneycontrol.com/india/stockpricequote/pharmaceuticals/lupin/L',
    EPS: 64.03,
    Divident: 375,
    CurrentStockPrice: 1475.6,
    currentRatio: 3.15,
    dividentYeild: '0.51%' },
  { name: 'Hindustan Zinc Ltd.',
    industry: 'METALS',
    symbol: 'HINDZINC',
    url: 'http://www.moneycontrol.com/india/stockpricequote/metalsnonferrous/hindustanzinc/HZ',
    EPS: 19.33,
    Divident: 1,
    CurrentStockPrice: 319.8,
    currentRatio: 2.44,
    dividentYeild: '8.67%' },
  { name: 'V-Guard Industries Ltd.',
    industry: 'INDUSTRIAL MANUFACTURING',
    symbol: 'VGUARD',
    url: 'http://www.moneycontrol.com/india/stockpricequote/miscellaneous/vguardindustries/VI02',
    EPS: 37.12,
    Divident: 70,
    CurrentStockPrice: 212.5,
    currentRatio: 2.49,
    dividentYeild: '0.33%' },
  { name: 'Unichem Laboratories Ltd.',
    industry: 'PHARMA',
    symbol: 'UNICHEMLAB',
    url: 'http://www.moneycontrol.com/india/stockpricequote/pharmaceuticals/unichemlaboratories/UL02',
    EPS: 11.07,
    Divident: 100,
    CurrentStockPrice: 270.4,
    currentRatio: 2.37,
    dividentYeild: '0.74%' },
  { name: 'SJVN Ltd.',
    industry: 'ENERGY',
    symbol: 'SJVN',
    url: 'http://www.moneycontrol.com/india/stockpricequote/powergenerationdistribution/sjvn/S11',
    EPS: 3.4,
    Divident: 11,
    CurrentStockPrice: 33.65,
    currentRatio: 6.09,
    dividentYeild: '3.26%' },
  { name: 'Torrent Pharmaceuticals Ltd.',
    industry: 'PHARMA',
    symbol: 'TORNTPHARM',
    url: 'http://www.moneycontrol.com/india/stockpricequote/pharmaceuticals/torrentpharmaceuticals/TP06',
    EPS: 104.2,
    Divident: 700,
    CurrentStockPrice: 1254.4,
    currentRatio: 2.07,
    dividentYeild: '2.79%' },
  { name: 'Torrent Power Ltd.',
    industry: 'ENERGY',
    symbol: 'TORNTPOWER',
    url: 'http://www.moneycontrol.com/india/stockpricequote/powergenerationdistribution/torrentpower/TP14',
    EPS: 16.98,
    Divident: 45,
    CurrentStockPrice: 202.2,
    currentRatio: 2.12,
    dividentYeild: '2.24%' },
  { name: 'Greaves Cotton Ltd.',
    industry: 'INDUSTRIAL MANUFACTURING',
    symbol: 'GREAVESCOT',
    url: 'http://www.moneycontrol.com/india/stockpricequote/engines/greavescotton/GC20',
    EPS: 8.14,
    Divident: 275,
    CurrentStockPrice: 139,
    currentRatio: 2.89,
    dividentYeild: '3.96%' },
  { name: 'Tata Consultancy Services Ltd.',
    industry: 'IT',
    symbol: 'TCS',
    url: 'http://www.moneycontrol.com/india/stockpricequote/computerssoftware/tataconsultancyservices/TCS',
    EPS: 116.13,
    Divident: 4,
    CurrentStockPrice: 2341.7,
    currentRatio: 3.01,
    dividentYeild: '1.85%' },
  { name: 'Shriram City Union Finance Ltd.',
    industry: 'FINANCIAL SERVICES',
    symbol: 'SHRIRAMCIT',
    url: 'http://www.moneycontrol.com/india/stockpricequote/financeleasinghirepurchase/shriramcityunionfinance/SCU',
    EPS: 80.36,
    Divident: 150,
    CurrentStockPrice: 1950,
    currentRatio: 2.19,
    dividentYeild: '0.77%' },
  { name: 'Divi\'s Laboratories Ltd.',
    industry: 'PHARMA',
    symbol: 'DIVISLAB',
    url: 'http://www.moneycontrol.com/india/stockpricequote/pharmaceuticals/divislaboratories/DL03',
    EPS: 41.73,
    Divident: 500,
    CurrentStockPrice: 757.7,
    currentRatio: 6.04,
    dividentYeild: '1.32%' },
  { name: 'Oberoi Realty Ltd.',
    industry: 'CONSTRUCTION',
    symbol: 'OBEROIRLTY',
    url: 'http://www.moneycontrol.com/india/stockpricequote/constructioncontractingrealestate/oberoirealty/OR',
    EPS: 14.01,
    Divident: 20,
    CurrentStockPrice: 332.25,
    currentRatio: 4.04,
    dividentYeild: '0.60%' },
  { name: 'Oil India Ltd.',
    industry: 'ENERGY',
    symbol: 'OIL',
    url: 'http://www.moneycontrol.com/india/stockpricequote/oildrillingandexploration/oilindia/OI13',
    EPS: 38.76,
    Divident: 160,
    CurrentStockPrice: 345.45,
    currentRatio: 5.06,
    dividentYeild: '4.63%' },
  { name: 'Tech Mahindra Ltd.',
    industry: 'IT',
    symbol: 'TECHM',
    url: 'http://www.moneycontrol.com/india/stockpricequote/computerssoftware/techmahindra/TM4',
    EPS: 33.27,
    Divident: 240,
    CurrentStockPrice: 496.7,
    currentRatio: 2.29,
    dividentYeild: '2.41%' },
  { name: 'Tata Coffee Ltd.',
    industry: 'CONSUMER GOODS',
    symbol: 'TATACOFFEE',
    url: 'http://www.moneycontrol.com/india/stockpricequote/plantationsteacoffee/tatacoffee/TC14',
    EPS: 5.49,
    Divident: 130,
    CurrentStockPrice: 130.9,
    currentRatio: 2.05,
    dividentYeild: '1.00%' },
  { name: 'Mahindra Lifespace Developers Ltd.',
    industry: 'CONSTRUCTION',
    symbol: 'MAHLIFE',
    url: 'http://www.moneycontrol.com/india/stockpricequote/constructioncontractingcivil/mahindralifespacedevelopers/MLD',
    EPS: 25.47,
    Divident: 60,
    CurrentStockPrice: 352.65,
    currentRatio: 2.6,
    dividentYeild: '1.70%' },
  { name: 'MindTree Ltd.',
    industry: 'IT',
    symbol: 'MINDTREE',
    url: 'http://www.moneycontrol.com/india/stockpricequote/computerssoftware/mindtree/MT13',
    EPS: 36.05,
    Divident: 160,
    CurrentStockPrice: 461.05,
    currentRatio: 2.18,
    dividentYeild: '3.47%' },
  { name: 'National Aluminium Co. Ltd.',
    industry: 'METALS',
    symbol: 'NATIONALUM',
    url: 'http://www.moneycontrol.com/india/stockpricequote/aluminium/nationalaluminiumcompany/NAC',
    EPS: 2.84,
    Divident: 40,
    CurrentStockPrice: 65.65,
    currentRatio: 3.25,
    dividentYeild: '3.05%' },
  { name: 'Coal India Ltd.',
    industry: 'METALS',
    symbol: 'COALINDIA',
    url: 'http://www.moneycontrol.com/india/stockpricequote/miningminerals/coalindia/CI11',
    EPS: 25.87,
    Divident: 274,
    CurrentStockPrice: 323,
    currentRatio: 3.22,
    dividentYeild: '8.48%' },
  { name: 'Kansai Nerolac Paints Ltd.',
    industry: 'CONSUMER GOODS',
    symbol: 'KANSAINER',
    url: 'http://www.moneycontrol.com/india/stockpricequote/paintsvarnishes/kansainerolacpaints/KNP',
    EPS: 16.53,
    Divident: 305,
    CurrentStockPrice: 358,
    currentRatio: 2.57,
    dividentYeild: '0.85%' },
  { name: 'Grindwell Norton Ltd.',
    industry: 'INDUSTRIAL MANUFACTURING',
    symbol: 'GRINDWELL',
    url: 'http://www.moneycontrol.com/india/stockpricequote/abrasives/grindwellnorton/GN',
    EPS: 18.34,
    Divident: 130,
    CurrentStockPrice: 330,
    currentRatio: 2.15,
    dividentYeild: '1.96%' },
  { name: 'eClerx Services Ltd.',
    industry: 'IT',
    symbol: 'ECLERX',
    url: 'http://www.moneycontrol.com/india/stockpricequote/computerssoftwaremediumsmall/eclerxservices/eS06',
    EPS: 72.97,
    Divident: 10,
    CurrentStockPrice: 1403.05,
    currentRatio: 6.83,
    dividentYeild: '0.07%' },
  { name: 'Zensar Technolgies Ltd.',
    industry: 'IT',
    symbol: 'ZENSARTECH',
    url: 'http://www.moneycontrol.com/india/stockpricequote/computerssoftware/zensartechnologies/ZT02',
    EPS: 52.48,
    Divident: 120,
    CurrentStockPrice: 915.5,
    currentRatio: 6.45,
    dividentYeild: '1.31%' },
  { name: 'Mayur Uniquoters Ltd.',
    industry: 'TEXTILES',
    symbol: 'MAYURUNIQ',
    url: 'http://www.moneycontrol.com/india/stockpricequote/plastics/mayuruniquoters/MU',
    EPS: 17.19,
    Divident: 70,
    CurrentStockPrice: 372.05,
    currentRatio: 3.52,
    dividentYeild: '0.95%' },
  { name: 'Infosys Ltd.',
    industry: 'IT',
    symbol: 'INFY',
    url: 'http://www.moneycontrol.com/india/stockpricequote/computerssoftware/infosys/IT',
    EPS: 68.73,
    Divident: 485,
    CurrentStockPrice: 954.1,
    currentRatio: 2.97,
    dividentYeild: '2.54%' },
  { name: 'HCL Technologies Ltd.',
    industry: 'IT',
    symbol: 'HCLTECH',
    url: 'http://www.moneycontrol.com/india/stockpricequote/computerssoftware/hcltechnologies/HCL02',
    EPS: 33.56,
    Divident: 800,
    CurrentStockPrice: 818.8,
    currentRatio: 3.8,
    dividentYeild: '1.95%' },
  { name: 'Nilkamal Ltd.',
    industry: 'INDUSTRIAL MANUFACTURING',
    symbol: 'NILKAMAL',
    url: 'http://www.moneycontrol.com/india/stockpricequote/plastics/nilkamal/NP08',
    EPS: 69.62,
    Divident: 70,
    CurrentStockPrice: 1727.65,
    currentRatio: 2.07,
    dividentYeild: '0.40%' },
  { name: 'Bajaj Holdings & Investment Ltd.',
    industry: 'FINANCIAL SERVICES',
    symbol: 'BAJAJHLDNG',
    url: 'http://www.moneycontrol.com/india/stockpricequote/financeinvestments/bajajholdingsinvestment/BHI',
    EPS: 114.16,
    Divident: 325,
    CurrentStockPrice: 2059.95,
    currentRatio: 10.97,
    dividentYeild: '1.57%' },
  { name: 'FDC Ltd.',
    industry: 'PHARMA',
    symbol: 'FDC',
    url: 'http://www.moneycontrol.com/india/stockpricequote/pharmaceuticals/fdc/FDC',
    EPS: 8.82,
    Divident: 225,
    CurrentStockPrice: 210.45,
    currentRatio: 3.03,
    dividentYeild: '1.07%' },
  { name: 'Persistent Systems Ltd.',
    industry: 'IT',
    symbol: 'PERSISTENT',
    url: 'http://www.moneycontrol.com/india/stockpricequote/computerssoftware/persistentsystems/PS15',
    EPS: 33.18,
    Divident: 80,
    CurrentStockPrice: 616.5,
    currentRatio: 5.2,
    dividentYeild: '1.30%' },
  { name: 'KPIT Technologies Ltd.',
    industry: 'IT',
    symbol: 'KPIT',
    url: 'http://www.moneycontrol.com/india/stockpricequote/computerssoftwaremediumsmall/kpittechnologies/KPI02',
    EPS: 10.75,
    Divident: 110,
    CurrentStockPrice: 134.95,
    currentRatio: 2.76,
    dividentYeild: '1.63%' },
  { name: 'Wipro Ltd.',
    industry: 'IT',
    symbol: 'WIPRO',
    url: 'http://www.moneycontrol.com/india/stockpricequote/computerssoftware/wipro/W',
    EPS: 32.78,
    Divident: 300,
    CurrentStockPrice: 466.5,
    currentRatio: 2.71,
    dividentYeild: '1.28%' },
  { name: 'Engineers India Ltd.',
    industry: 'CONSTRUCTION',
    symbol: 'ENGINERSIN',
    url: 'http://www.moneycontrol.com/india/stockpricequote/infrastructuregeneral/engineersindia/EI14',
    EPS: 7.67,
    Divident: 80,
    CurrentStockPrice: 156.6,
    currentRatio: 2.45,
    dividentYeild: '2.55%' },
  { name: 'Bliss GVS Pharma Ltd.',
    industry: 'PHARMA',
    symbol: 'BLISSGVS',
    url: 'http://www.moneycontrol.com/india/stockpricequote/miscellaneous/blissgvspharma/BGV',
    EPS: 6.36,
    Divident: 50,
    CurrentStockPrice: 154.45,
    currentRatio: 2.85,
    dividentYeild: '0.32%' },
  { name: 'Kaveri Seed Company Ltd.',
    industry: 'CONSUMER GOODS',
    symbol: 'KSCL',
    url: 'http://www.moneycontrol.com/india/stockpricequote/miscellaneous/kaveriseedcompany/KSC01',
    EPS: 25.65,
    Divident: 125,
    CurrentStockPrice: 477.9,
    currentRatio: 2.75,
    dividentYeild: '0.52%' },
  { name: 'Suven Life Sciences Ltd.',
    industry: 'PHARMA',
    symbol: 'SUVEN',
    url: 'http://www.moneycontrol.com/india/stockpricequote/pharmaceuticals/suvenlifesciences/SLS01',
    EPS: 7.46,
    Divident: 200,
    CurrentStockPrice: 182,
    currentRatio: 4.48,
    dividentYeild: '1.10%' },
  { name: 'NMDC Ltd.',
    industry: 'METALS',
    symbol: 'NMDC',
    url: 'http://www.moneycontrol.com/india/stockpricequote/miningminerals/nmdc/NMD02',
    EPS: 7.64,
    Divident: 1,
    CurrentStockPrice: 146.45,
    currentRatio: 6.34,
    dividentYeild: '7.52%' },
  { name: 'Sonata Software Ltd.',
    industry: 'IT',
    symbol: 'SONATSOFTW',
    url: 'http://www.moneycontrol.com/india/stockpricequote/computerssoftwaremediumsmall/sonatasoftware/SS42',
    EPS: 11.17,
    Divident: 900,
    CurrentStockPrice: 196.1,
    currentRatio: 2.74,
    dividentYeild: '4.58%' },
  { name: 'TV Today Network Ltd.',
    industry: 'MEDIA & ENTERTAINMENT',
    symbol: 'TVTODAY',
    url: 'http://www.moneycontrol.com/india/stockpricequote/mediaentertainment/tvtodaynetwork/TVT',
    EPS: 15.81,
    Divident: 35,
    CurrentStockPrice: 276.9,
    currentRatio: 2.95,
    dividentYeild: '0.63%' },
  { name: 'Gujarat Mineral Development Corporation Ltd.',
    industry: 'METALS',
    symbol: 'GMDCLTD',
    url: 'http://www.moneycontrol.com/india/stockpricequote/miningminerals/gujaratmineraldevelopmentcorporation/GMD',
    EPS: 7.55,
    Divident: 150,
    CurrentStockPrice: 117.85,
    currentRatio: 4.41,
    dividentYeild: '2.55%' },
  { name: 'NLC India Ltd.',
    industry: 'ENERGY',
    symbol: 'NLCINDIA',
    url: 'http://www.moneycontrol.com/india/stockpricequote/powergenerationdistribution/nlcindia/NLC',
    EPS: 7.18,
    Divident: 30,
    CurrentStockPrice: 97.4,
    currentRatio: 3.42,
    dividentYeild: '3.09%' } ];

var babyParse = require('babyparse');
var fs = require('fs');
var csv = babyParse.unparse(companies);
var date = new Date();
fs.writeFileSync(date.getTime()+"-output.csv", csv);